version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/kotlin"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "Attect"
    labels:
      - "dependencies"
      - "kotlin"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Attect"
    labels:
      - "dependencies"
      - "github-actions"
