Args = --no-fallback \
       --enable-http \
       --enable-https \
       -H:+ReportExceptionStackTraces \
       --initialize-at-build-time=kotlin \
       --initialize-at-run-time=app.muka.project.kquickjs \
       --report-unsupported-elements-at-runtime
